services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - database
      - node

  database:
    image: mariadb:10.5.8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: p2207127
      MYSQL_USER: p2207127
      MYSQL_PASSWORD: 12207127
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  node:
    image: node:16
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: ["npm", "run", "watch"]


volumes:
  db_data:
  database_data: